import PDFDocument from 'pdfkit';

interface AnalysisData {
  smiles: string;
  compoundName: string | null;
  formula: string | null;
  target: string | null;
  disease: string | null;
  createdAt: Date;
}

interface ReportData {
  executiveSummary: string;
  keySimilarPatents: string;
  noveltyConcerns: string;
  manualReviewList: string;
  recommendation: string;
  rationale: string;
  createdAt: Date;
}

/**
 * Generate a PDF report from analysis and report data.
 */
export async function generatePdf(
  analysis: AnalysisData,
  report: ReportData
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 50, right: 50 },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Title
    doc
      .fontSize(22)
      .font('Helvetica-Bold')
      .text('PatentPilot — FTO Analysis Report', { align: 'center' });

    doc.moveDown(0.5);
    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#666666')
      .text(`Generated: ${new Date(report.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });

    doc.moveDown(1);

    // Recommendation Badge
    const recColors: Record<string, string> = {
      low_risk: '#16a34a',
      expert_review: '#d97706',
      high_risk: '#dc2626',
    };
    const recLabels: Record<string, string> = {
      low_risk: 'LOW PATENT RISK',
      expert_review: 'REQUIRES EXPERT REVIEW',
      high_risk: 'HIGH PATENT RISK',
    };

    const recColor = recColors[report.recommendation] || '#666666';
    const recLabel = recLabels[report.recommendation] || report.recommendation.toUpperCase();

    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor(recColor)
      .text(`Overall Recommendation: ${recLabel}`, { align: 'center' });

    doc.moveDown(1);

    // Molecule Info
    doc.fillColor('#000000');
    addSection(doc, 'Molecule Information');
    addField(doc, 'SMILES', analysis.smiles);
    if (analysis.compoundName) addField(doc, 'Compound', analysis.compoundName);
    if (analysis.formula) addField(doc, 'Formula', analysis.formula);
    if (analysis.target) addField(doc, 'Target', analysis.target);
    if (analysis.disease) addField(doc, 'Disease/Indication', analysis.disease);

    doc.moveDown(0.5);

    // Report Sections
    addSection(doc, 'Executive Summary');
    addBody(doc, report.executiveSummary);

    addSection(doc, 'Key Similar Patents');
    addBody(doc, report.keySimilarPatents);

    addSection(doc, 'Potential Novelty Concerns');
    addBody(doc, report.noveltyConcerns);

    addSection(doc, 'Patents Requiring Manual Review');
    addBody(doc, report.manualReviewList);

    addSection(doc, 'Scoring Rationale');
    addBody(doc, report.rationale);

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor('#999999')
      .text(
        'Disclaimer: This report is generated by PatentPilot using automated patent retrieval and AI analysis. ' +
          'It is not legal advice. Patent expiry estimates are based on publication date + 20 years and may not reflect ' +
          'actual patent status. Always consult a patent attorney for definitive FTO assessments.',
        { align: 'center' }
      );

    doc.end();
  });
}

function addSection(doc: PDFKit.PDFDocument, title: string): void {
  doc.moveDown(0.8);
  doc
    .fontSize(13)
    .font('Helvetica-Bold')
    .fillColor('#1a1a1a')
    .text(title);
  doc.moveDown(0.3);
  // Underline
  const y = doc.y;
  doc
    .strokeColor('#cccccc')
    .lineWidth(0.5)
    .moveTo(50, y)
    .lineTo(545, y)
    .stroke();
  doc.moveDown(0.3);
}

function addField(doc: PDFKit.PDFDocument, label: string, value: string): void {
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .fillColor('#333333')
    .text(`${label}: `, { continued: true })
    .font('Courier')
    .fillColor('#1a1a1a')
    .text(value);
}

function addBody(doc: PDFKit.PDFDocument, text: string): void {
  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('#333333')
    .text(text || 'No information available.', {
      lineGap: 3,
      paragraphGap: 5,
    });
}
